#!/bin/bash
#
# This uses GitHub Container Registry.
# So you need to login ghcr.io with Personal Access Token which have scope read:packages at least.
#
# Example:
#
#   cat | docker login ghcr.io -u USERNAME --password-stdin
#   (type your PAT and Ctrl-D twice)

set -eu

docker compose run --rm -p 4000:4000 jekyll jekyll server -H 0.0.0.0 "$@"
